server {
	listen 80;
	server_name localhost;
	root /usr/share/nginx/html;
	gzip on;
	gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	location /health {
		add_header Content-Type application/json;

		return 200 "{\"status\": \"up\"}";
	}

	# do not cache anything other than above static
	location ~ ^/(.*) {
		try_files /$1 /index.html =404;
		expires -1;
	}

}
